#!/usr/bin/env node
/**
 * Render Y-API's published price file as a markdown table.
 *
 * Everything here is read from https://y-api.bestvirtualgoods.com/pricing.json
 * — no key needed, no number hard-coded. Two rules the script follows, because
 * breaking either one produces a table that quietly contradicts the site:
 *
 * 1. The cash price is recomputed from `credit_price / top_up.quota_rate`
 *    rather than copied from `cash_price`. If the two disagree the script
 *    fails loudly instead of publishing a number nobody can reconcile.
 *    The rate itself is read from the file, never assumed.
 * 2. `vs_official.vendor_cheaper_on_cached_input` is printed as-is, alongside
 *    `vs_official.caveats`. A row can carry the flag and still be excluded
 *    from the site's own "we lose on cache" count — that happens when the
 *    vendor price behind it is marked `historical-price`. Printing the flag
 *    without the caveat is how a reader ends up believing the wrong count.
 *
 * Usage:
 *   node price-table.mjs > table.md
 *   PRICE_JSON=./pricing.json node price-table.mjs    # read a local copy
 *
 * The env-var path exists because rendering has to be reproducible offline:
 * if a run of this script ever disagrees with the committed table.md, you need
 * to be able to pin the input and diff the two without depending on the network.
 */
const SOURCE = 'https://y-api.bestvirtualgoods.com/pricing.json'
const LOCAL = process.env.PRICE_JSON

const fail = (msg) => {
  console.error(`price-table: ${msg}`)
  process.exit(1)
}

const num = (n) => {
  if (n === 0) return '0'
  if (typeof n !== 'number' || Number.isNaN(n)) return '—'
  return String(Number(n.toFixed(6)))
}

let data
if (LOCAL) {
  const { readFileSync } = await import('node:fs')
  data = JSON.parse(readFileSync(LOCAL, 'utf8'))
} else {
  const res = await fetch(SOURCE, {
    headers: { 'user-agent': 'y-api-price-tracker (github action)', accept: 'application/json' },
  }).catch((e) => fail(`cannot reach ${SOURCE}: ${e.message}`))
  if (!res.ok) fail(`${SOURCE} returned HTTP ${res.status}`)
  data = await res.json()
}
const models = data.models
if (!Array.isArray(models) || models.length === 0) fail('no models in the price file')

const rate = data.top_up?.quota_rate
if (typeof rate !== 'number' || rate <= 0) fail('top_up.quota_rate missing or not a positive number')

// Rule 1: recompute and reconcile before trusting the file's own cash_price.
const drift = []
for (const m of models) {
  for (const side of ['input', 'output']) {
    const credit = m.credit_price?.[side]
    const cash = m.cash_price?.[side]
    if (typeof credit !== 'number' || typeof cash !== 'number') continue
    if (Math.abs(credit / rate - cash) > 1e-9) {
      drift.push(`${m.id}.${side}: published ${cash}, recomputed ${credit / rate}`)
    }
  }
}
if (drift.length) fail(`cash_price disagrees with credit_price / quota_rate:\n  ${drift.join('\n  ')}`)

const now = new Date().toISOString().slice(0, 10)
const promo = data.top_up
const rateLine = promo?.is_promotional
  ? `Top-up rate: $1 paid = $${rate} of credit — **promotional**, reverts to 1:${promo.regular_quota_rate}; end date ${
      promo.promotional_ends_at ? `announced as ${promo.promotional_ends_at}` : 'not announced'
    }.`
  : `Top-up rate: $1 paid = $${rate} of credit.`

const byCash = [...models].sort((a, b) => {
  const pa = a.credit_price?.input ?? 0
  const pb = b.credit_price?.input ?? 0
  if (pa !== pb) return pa - pb
  return String(a.id).localeCompare(String(b.id))
})

const lines = []
lines.push('# Y-API price table (cash)')
lines.push('')
lines.push(
  `Generated by \`price-table.mjs\` from <${SOURCE}> — source snapshot \`${data.synced_at ?? 'unknown'}\`, rendered ${now}.`,
)
lines.push('')
lines.push(rateLine)
lines.push('')
lines.push(
  'Credit is what the account balance is charged; cash is what leaves your card (`credit_price / top_up.quota_rate`). Compare the cash columns against other providers — that is what their list prices are quoted in.',
)
lines.push('')
lines.push(`## The catalog — ${models.length} models`)
lines.push('')
lines.push('| Model | Vendor | Credit in | Credit out | Cash in | Cash out |')
lines.push('| --- | --- | --- | --- | --- | --- |')
for (const m of byCash) {
  lines.push(
    `| \`${m.id}\` | ${m.vendor} | ${num(m.credit_price?.input)} | ${num(m.credit_price?.output)} | ${num(
      m.cash_price?.input,
    )} | ${num(m.cash_price?.output)} |`,
  )
}
lines.push('')
lines.push('Per 1M tokens, USD. Sorted by credit input price.')
lines.push('')

const compared = models.filter((m) => m.vs_official)
lines.push(`## Against the vendor's own list price — ${compared.length} of ${models.length} models`)
lines.push('')
lines.push('| Model | Our cash in | Vendor in | × ours | Vendor out | Cache-cheaper? | Caveats | Verified | Source |')
lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |')
for (const m of compared) {
  const v = m.vs_official
  const caveats = (v.caveats ?? []).join(', ') || '—'
  lines.push(
    `| \`${m.id}\` | ${num(m.cash_price?.input)} | ${num(v.input)} | ${num(v.input_multiple)}× | ${num(v.output)} | ${
      v.vendor_cheaper_on_cached_input ? 'yes' : 'no'
    } | ${caveats} | ${v.verified_at} | [link](${v.source}) |`,
  )
}
lines.push('')
lines.push(
  '`Cache-cheaper?` is the file\'s own `vs_official.vendor_cheaper_on_cached_input` flag: the vendor\'s cached-input rate is below our cash input price. Read it together with the `Caveats` column — a row marked `historical-price` is priced against a past vendor rate card and is not counted as a current loss on the Y-API site.',
)
lines.push('')
lines.push(
  `Models without a row here are ones where no vendor list price could be verified and cited. The file states this explicitly rather than estimating: ${models.length - compared.length} of ${models.length} are in that position.`,
)
lines.push('')

process.stdout.write(lines.join('\n'))
